services:
  gateway:
    image: registry.gitlab.com/segmentation964330/service/gateway
    build:
      context: ./gateway
    ports:
      - "80:8000"
    volumes:
      - ./artifacts/images:/home/artifacts/images
      - ./artifacts/logs:/home/artifacts/logs
      - ./artifacts/models:/home/artifacts/models
    tty: true
    stdin_open: false
