services:
  redis:
    container_name: redis
    image: redis:7.0.15-alpine3.20
    command: redis-server --bind redis --port 6379
    tty: true
    stdin_open: true
  inference:
    container_name: inference
    image: registry.gitlab.com/segmentation964330/service/inference
    build:
      context: ./inference
    volumes:
      - ./artifacts/images:/home/artifacts/images
      - ./artifacts/logs:/home/artifacts/logs
      - ./artifacts/models:/home/artifacts/models
    depends_on:
      - redis
    tty: true
    stdin_open: true
  gateway:
    container_name: gateway
    image: registry.gitlab.com/segmentation964330/service/gateway
    build:
      context: ./gateway
    volumes:
      - ./artifacts/images:/home/artifacts/images
      - ./artifacts/logs:/home/artifacts/logs
    depends_on:
      - redis
    tty: true
    stdin_open: true
  nginx:
    container_name: nginx
    image: registry.gitlab.com/segmentation964330/service/nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - gateway
    tty: true
    stdin_open: true