services:
  gateway:
    container_name: gateway
    image: registry.gitlab.com/segmentation964330/service/gateway
    build:
      context: ./gateway
    volumes:
      - ./artifacts/images:/home/artifacts/images
      - ./artifacts/logs:/home/artifacts/logs
      - ./artifacts/models:/home/artifacts/models
    tty: true
    stdin_open: true
  nginx:
    container_name: nginx
    image: registry.gitlab.com/segmentation964330/service/nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - gateway
    tty: true
    stdin_open: true