services:
  segmentation_redis:
    image: redis:7.0.15-alpine3.20
    command: redis-server --bind segmentation_redis --port 6379
    tty: true
    stdin_open: true
    networks:
    - shared_mesh
  segmentation_inference:
    image: registry.gitlab.com/erichuangt/segmentation/inference
    build:
      context: ./inference
    volumes:
      - ../artifacts/images:/home/artifacts/images
      - ../artifacts/logs:/home/artifacts/logs
      - ../artifacts/models:/home/artifacts/models
      - ../artifacts/db:/home/artifacts/db
    depends_on:
      - segmentation_redis
    tty: true
    stdin_open: true
    networks:
    - shared_mesh
  segmentation_gateway:
    image: registry.gitlab.com/erichuangt/segmentation/gateway
    build:
      context: ./gateway
    volumes:
      - ../artifacts/images:/home/artifacts/images
      - ../artifacts/logs:/home/artifacts/logs
    depends_on:
      - segmentation_redis
    tty: true
    stdin_open: true
    networks:
    - shared_mesh

networks:
  shared_mesh:
    name: erichuangt_network
