name: build-deploy-docker
on:
  push:
    branches:
      - main
  pull-request:
    branches:
      - main

jobs:
  build-gateway:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: ls
