name: build-deploy-docker
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GITLAB_REGISTRY_USERNAME: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
  GITLAB_REGISTRY_TOKEN: ${{ secrets.GITLAB_REGISTRY_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Build, Push, Deploy.
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USERNAME }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          envs: GITLAB_REGISTRY_USERNAME, GITLAB_REGISTRY_TOKEN
          script: |
            echo "$GITLAB_REGISTRY_TOKEN" | docker login registry.gitlab.com -u "$GITLAB_REGISTRY_USERNAME" --password-stdin
            ls -a