name: build-deploy-docker
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-gateway:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repo.
        uses: actions/checkout@v4
      - name: Setup buildx
        run:  docker buildx create --use
      - name: Sign in to segmentation gitlab registry.
        env:
          GITLAB_REGISTRY_USERNAME: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
          GITLAB_REGISTRY_TOKEN: ${{ secrets.GITLAB_REGISTRY_TOKEN }}
        run: echo "$GITLAB_REGISTRY_TOKEN" | docker login registry.gitlab.com -u "$GITLAB_REGISTRY_USERNAME" --password-stdin
      - name: Build gateway image.
        run: |
          docker buildx build \
            --file ./gateway \
            --platform linux/arm64 \
            -t registry.gitlab.com/segmentation964330/service/gateway \
            --push .
      - name: Check img.
        run: docker images
